# docker-compose.yaml

version: "3.8"

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: sre-postgres
    environment:
      POSTGRES_USER: examuser
      POSTGRES_PASSWORD: exampassword
      POSTGRES_DB: examdb
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"
    networks:
      - sre_net

  #networks:
  #  sre_net:
  #    driver: bridge

  # python api backend
  backend:
    build: ./app/backend
    container_name: sre-backend
    environment:
      #its uses the DNS name "postgres" to connect
      - DATABASE_URL=postgresql://examuser:exampassword@postgres:5432/examdb
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=quantum-sre-backend 
      - OTEL_TRACES_EXPORTER=none # temparary disable until we set up the TEMPO 
      - OTEL_METRICS_EXPORTER=otlp
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - otel-collector 
    networks:
      - sre_net
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"

  # the Nginx web server and reverse proxy

  nginx:
    image: nginx:1.25.1-alpine
    container_name: sre-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - sre_net
    logging:
      driver: "json-file"
      options:
        tag: "{{.Name}}"

# Node Exporter (Hardware metrics)

  node-exporter:
    image: prom/node-exporter:latest
    container_name: sre-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
    networks:
      - sre_net

# Prometheus (The metrics database)
  prometheus:
    image: prom/prometheus:latest
    container_name: sre-prometheus 
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus 
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - sre_net

# telegraf (for database metrics )
  telegraf:
    image: telegraf:1.28-alpine
    container_name: sre-telegraf
    restart: unless-stopped
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "9273:9273"
    depends_on:
      - postgres
    networks:
      - sre_net

#otel collector 
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: sre-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" #otlp gRPC reciver
      - "8889:8889" # prometheus metrics exporter 
    networks:
      - sre_net  

volumes:
  prometheus_data:

networks:
  sre_net:
    driver: bridge
