[agent]
    interval = "10s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000

#output: expose metrics on port 9273 for the prometheus to scrape

[[outputs.prometheus_client]]
    listen = ":9273"

#input:connect to our postgreSQL container 

[[inputs.postgresql]]
    #using the internal docker dns postgres and the credentials we set earlier 
    address = "postgres://examuser:exampassword@postgres:5432/examdb?sslmode=disable"
    databases = ["examdb"]
